# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: NoCloudCLI
before:
  hooks:
    - go mod tidy
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    binary: nocloud
    ldflags:
      - -s -w -X github.com/slntopp/nocloud-cli/cmd.VERSION={{.Version}}
    tags:
      - nocloud
      - cli
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "nocloud_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - default
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - examples/**/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  mode: keep-existing
  draft: true
  github:
    owner: slntopp
    name: nocloud-cli

brews:
  -
    name: nocloud
    homepage: "https://github.com/slntopp/nocloud"
    license: "Apache-2.0"
    description: "NoCloud Platform CLI"
    caveats: "Start with nocloud help login ;)"
    tap:
      owner: slntopp
      name: homebrew-nocloud
    commit_author:
      name: slntopp
      email: info@slnt-opp.xyz

nfpms:
  - package_name: nocloud
    homepage: https://github.com/slntopp/nocloud
    maintainer: slntopp info@slnt-opp.xyz
    description: NoCloud Platform CLI
    license: Apache 2.0
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - default
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux

    formats:
      - deb
      - rpm

    dependencies:
      - git


    # Version Metadata (previously deb.metadata).
    # Default is extracted from `version` if it is semver compatible.
    # Setting metadata might interfere with version comparisons depending on the packager.
    version_metadata: git

    # Section.
    section: default

    # Priority.
    priority: extra